

rootProject.buildscript {
    repositories {
        mavenLocal()
        google()
        //jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://maven.aliyun.com/repository/jcenter'
        }
        maven { url 'https://nexus.hss01248.tech/repository/maven-releases/' }
        maven {
            url 'https://maven.aliyun.com/nexus/content/groups/public/'
        }
        all { ArtifactRepository repo ->
            if (repo instanceof MavenArtifactRepository) {
                def url = repo.url.toString()
                if (url.startsWith('https://jcenter.bintray.com')) {
                    remove repo
                }
            }
        }
    }


}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        google()
        //jcenter()
        maven {
            url 'https://maven.aliyun.com/repository/jcenter'
        }
        maven { url 'https://jitpack.io' }
        maven { url 'https://github.com/link-u/AndroidGlideAvifDecoder/raw/master/repository' }
        maven { url 'https://nexus.hss01248.tech/repository/maven-releases/' }
        all { ArtifactRepository repo ->
            def url = repo.url.toString()
            if ((repo instanceof MavenArtifactRepository) &&  url.startsWith('https://jcenter.bintray.com')) {
                project.logger.lifecycle 'Repository ${repo.url} replaced by $REPOSITORY_URL .'
                remove repo
            }
        }
        def REPOSITORY_URL = 'https://maven.aliyun.com/nexus/content/groups/public/'
        maven {
            url REPOSITORY_URL
        }

    }
}

static  void assignRepos(Project project){
    boolean  useAliyun2 = false
    project.repositories {
        if(useAliyun2){
            maven {
                url 'https://maven.aliyun.com/repository/central'
            }
            maven {
                url 'https://maven.aliyun.com/repository/jcenter'
            }
            maven {
                url 'https://maven.aliyun.com/repository/apache-snapshots'
            }
            maven {
                url 'https://maven.aliyun.com/repository/google'
            }
            maven {
                url 'https://maven.aliyun.com/repository/spring'
            }
        }

        mavenLocal()
        mavenCentral()
        google()
        //jcenter()
        maven {
            url 'https://maven.aliyun.com/repository/jcenter'
        }
        maven { url 'https://jitpack.io' }
        maven { url 'https://github.com/link-u/AndroidGlideAvifDecoder/raw/master/repository' }
        maven { url 'https://nexus.hss01248.tech/repository/maven-releases/' }
        all { ArtifactRepository repo ->
            def url = repo.url.toString()
            if ((repo instanceof MavenArtifactRepository) &&  url.startsWith('https://jcenter.bintray.com')) {
                project.logger.lifecycle 'Repository ${repo.url} replaced by $REPOSITORY_URL .'
                remove repo
            }
        }
        def REPOSITORY_URL = 'https://maven.aliyun.com/nexus/content/groups/public/'
        maven {
            url REPOSITORY_URL
        }
    }
}

