

rootProject.buildscript {
    repositories {
        mavenLocal()
        google()
        //jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://maven.aliyun.com/repository/jcenter'
        }
        maven { url 'https://nexus.hss01248.tech/repository/maven-releases/' }
        maven {
            url 'https://maven.aliyun.com/nexus/content/groups/public/'
        }
        all { ArtifactRepository repo ->
            if (repo instanceof MavenArtifactRepository) {
                def url = repo.url.toString()
                if (url.startsWith('https://jcenter.bintray.com')) {
                    remove repo
                }
            }
        }
    }


}

static  void assignRepos(Project project){
    boolean  useAliyun2 = false
    project.repositories {
        if(useAliyun2){
            maven {
                url 'https://maven.aliyun.com/repository/central'
            }
            maven {
                url 'https://maven.aliyun.com/repository/jcenter'
            }
            maven {
                url 'https://maven.aliyun.com/repository/apache-snapshots'
            }
            maven {
                url 'https://maven.aliyun.com/repository/google'
            }
            maven {
                url 'https://maven.aliyun.com/repository/spring'
            }
        }

        mavenLocal()
        /*     maven {
                 //加到了group里,直接使用maven-public, 无需显式使用jitpack_proxy2
                 url "https://nexus.hss01248.tech/repository/jitpack_proxy/"
                 *//*credentials{
                     username "cccc"
                     password "ccccc"
                 }*//*
             }*/
        mavenCentral()
        google()
        //jcenter()
        maven {
            url 'https://maven.aliyun.com/repository/jcenter'
        }
        maven { url 'https://jitpack.io' }
        maven { url 'https://github.com/link-u/AndroidGlideAvifDecoder/raw/master/repository' }
        maven { url 'https://nexus.hss01248.tech/repository/maven-releases/' }
        all { ArtifactRepository repo ->
            def url = repo.url.toString()
            if ((repo instanceof MavenArtifactRepository) &&  url.startsWith('https://jcenter.bintray.com')) {
                project.logger.lifecycle 'Repository ${repo.url} replaced by $REPOSITORY_URL .'
                remove repo
            }
        }
        def REPOSITORY_URL = 'https://maven.aliyun.com/nexus/content/groups/public/'
        maven {
            url REPOSITORY_URL
        }
    }
}

gradle.addProjectEvaluationListener(new ProjectEvaluationListener() {
    @Override
    void beforeEvaluate(Project project) {


    }

    @Override
    void afterEvaluate(Project project, ProjectState projectState) {
        assignRepos(project)
    }
})