-dontwarn okhttp3.**
-keep class okhttp3.**{*;}
-keep class com.tencent.mmkv.**{*;}
-keep class com.facebook.flipper.** { *; }
-keep class com.facebook.jni.** { *; }
-keep class com.facebook.jni.** { *; }
-keep class **.flipper.** { *; }
-keep class kotlin.reflect.** { *; }