plugins {
    id 'com.android.library'
}

android {
    namespace 'com.hss01248.logforaop'
    compileSdkVersion 36
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 36
        consumerProguardFiles "consumer-rules.pro"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api 'io.github.flyjingfish:androidaop-core:2.7.4'
    annotationProcessor 'io.github.flyjingfish:androidaop-apt:2.7.4'
}
